version = 1

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = false

[[analyzers]]
name = "rust"
enabled = true

[analyzers.meta]
<<<<<<< HEAD
msrv = "1.85.0"
=======
msrv = "1.80.0"
>>>>>>> 330eaee0f (chore(version): 2025.08.28.0-hotfix1)
